# Generated by Django 2.2.19 on 2021-04-13 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
        ('catalogo_permisos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, max_length=50)),
                ('time_span_days', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalogo_permisos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos', to='catalogo_permisos.CatalogoPermiso')),
                ('empleados', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos', to='empleados.Empleado')),
            ],
        ),
    ]
