# Generated by Django 2.2.19 on 2021-04-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
